#Contenedores que conforman el proyecto
services:
  artemis:
    # Cada contenedor que se define debe tener especificado de dónde coger la imagen para crearlo y su nombre
    image: apache/artemis:latest-alpine
    container_name: mini-amqp-artemis

    environment:
    # Desde el archivo .env coge las credenciales necesarias
      ARTEMIS_USER: ${ARTEMIS_USER}
      ARTEMIS_PASSWORD: ${ARTEMIS_PASSWORD}
      ANONYMOUS_LOGIN: "false"

    ports:
    # Puerto principal de mensajería
      - "61616:61616"
    # Consola web de administración
      - "8161:8161"

    volumes:
    # Crea un volumen persistente
      - artemis-data:/var/lib/artemis-instance

  consumer:
    build:
      context: ./consumer

    environment:
      AMQP_HOST: artemis
      AMQP_PORT: 61616
      AMQP_USER: ${ARTEMIS_USER}
      AMQP_PASSWORD: ${ARTEMIS_PASSWORD}
      AMQP_QUEUE: tracks.distribution::client-a.tracks
    
    depends_on:
      - artemis

    # Evita que el consumidor se ejecute automaticamente cada vez que se levanta el contenedor con: <docker compose up -d>. Queremos lanzarlo manualmente para pruebas
    profiles:
      - tools

volumes:
  artemis-data: